Add EventsExecutor
Handle intra-process communication

Move apis - Add constness

Create raw pointer version of Executor::execute_<ENTITY>

Remove exec mutex. Add comments

remove not needed APIs

Change how to add node gc's to entities collector

Remove comments

Use EventsExecutorEntitiesCollector

restore original StaticExecutorEntitiesCollector

remove includes

Handle timers from EventsExecutorEntitiesCollector

Not ready for rebuild stuff

Some cleaning

Some reorder

Use or discard previous events: Guard conditions

Implement spin some

Remove node from executor support

move execute entities to executor.cpp

Move apis

init entities collector at executor construction

reimplement timers heap -> timers queue

rename timers queue

update timers queue

Move code

Use lambdas directly

Handle default event types

Fix spinsome

Check rclcpp::ok before execute timers

Restore timers heap

Set interrupt guard condition callback

create TimersManager class, implement spin() variants for EventsExecutor and fix unit tests

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

add missing predicate to event_queue_cv wait

Update events_executor.cpp

Fix code style errors

Rename EventQ -> ExecutorEvent

rename set_guard_condition_callback -> set_callback

Rename to set_events_executor_callback

Rename to ExecutorEventCallback

remove unused handle_events() function

rename functions in unit-tests

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

fix linter errors

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

cleanup entities collector

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

add timers manager test and bug fixes

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Update test_timers_manager.cpp

override cancel

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Support events

void return on set_events_executor_callback

Update client.hpp

Update qos_event.hpp

clean add/remove node APIs and make sure that event callbacks are removed when destroying executor

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Revert "void return on set_events_executor_callback"

more thread safety and events executor test

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

remove atomic and use mutex to protect running_ flag

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

minor cleanup of comments and spin_some timeout

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

complete destruction callback implementation

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

remove prints

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

undo whitespace change

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

use std:: functions for heap and minor fixes

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

remove logs

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

fix unit tests

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

fix comments

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Add callback groups support

copy/paste fix

Add missing unsets

use emplace

Remove not needed unset_node_entities_callbacks

use insert

Adress comments

Remove not needed unset_node_entities_callbacks

fixes

Set gc's callback only if new node

Change set/unset node's notify guard condition location

Don't use weak_nodes list to unset guard conditions

Add nodes_notify_guard_conditions_ list

make sure that node does not get destroyed while unsetting guard condition

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

fix usage of destruction callback in waitables, add executor notifier

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

add comment

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

add functions for setting/unsetting guard conditions

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

add unit tests for callback groups and fix some issues

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Rename ExecutorEventCallback -> EventsExecutorCallback

make functions private

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

remove commented code

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

fix comments

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Add spin_some default arg

rename local_event_queue->execution_event_queue

Move rcutils/executor_event_types.h to rmw/

rename event types

rename set_events_executor_callback to set_listener_callback

Revert. set_listener_callback->set_events_executor_callback

Add vectors of entities weak pointers

Use map for weak pointers

Use ownership model on timers

Use unordered map

release timers ownership when stopping

Rename functions

Remove entity if expired

Remove entities if not previously removed

Check if not removed before anything

Optimize get_<entities>

rename entity identifiers

clarify comment

clarify comment

refactor timers_manager ownership

Reimplement onwership timers

Correct ownership timers

remove mutex not needed since new ownership model

Move using TimerPtr to private section

If a timer was removed, re-heapify vector

Revert "If a timer was removed, re-heapify vector"

This reverts commit 979ca878e27b83aafa4405daa978972a161800c3.

Revert "Move using TimerPtr to private section"

This reverts commit fc903e502d026f2d5cca7d45d15d9bf4574a1781.

rework timers manager weak ownership

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

undo wrong replace

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

cleanup linter errors

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

EventsExecutorEntitiesCollector: Use shared_from_this()

remove some unnecessary diffs

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

Update timers_manager.hpp documentation

Update doc

update APIs

Fix IPC on EventsExecutor and StaticSingle...

Add comment

Implement take_data on events_executor_notify_waitable

Compiler wants take_data defined on event_waitable.hpp

Implement take_data only on derived classes

Fix tests compilation

fix linter errors

Fix TimersHeap::validate_and_lock()

Fix uncrustify errors

Fix cppcheck

error: deallocuse - Dereferencing 'node_ptr' after
it is deallocated / released

Seems that:
NodeBaseInterface::WeakPtr node_weak_ptr(node_ptr);
causes the cppcheck to fail if node_ptr is used after creating
the weak pointer from it.

Reorder APIs arguments

Add events queue abstract class and implem

Apply PR suggestions

Fix ctests

EntitiesCollector not needed on events_queue

Add BoundedEventsQueue

Add unit tests for Simple and Bounded queues

Set size limit in constructor

Test all events queue APIs

Remove BoundedQueue, not ready yet for this

rename rmw_listener_cb_t->rmw_listener_callback_t

Implement no-op on IPC subscription

Check if valid msg before dispatch

Add log when ring buffer is full

restore line. This shouldn't happen any more

Fix size_t log type

remove log about full ring buffer

Ctests fixes

Check validity of executor pointer

use void * to pass executor ptr

Proper spin_some behaviour on EventsExecutor

rework spin_some & spin_all

spin_some and spin_all call spin_some_impl

Use timer_was_ready_at_tp

remove smart pointer definitions for virtual class

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

cleanup events executor class

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

rework events executor constructor

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

cleanup timers manager

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

new implementation of get_head_timeout_unsafe

Signed-off-by: Soragna, Alberto <alberto.soragna@gmail.com>

Rework executor callback data

Use entity_id to compute hash. Add comments

Use RMW renamed file

fix hash type

Update EventsExecutorCallbackData

Use RCLCPP_SMART_PTR_ALIASES_ONLY

Rename set_events_executor_callback->set_listener_callback